package server

import "time"

// https://mholt.github.io/json-to-go/

type AutoGenerated struct {
	Kind       string `json:"kind,omitempty"`
	APIVersion string `json:"apiVersion,omitempty"`
	Request    struct {
		UID  string `json:"uid,omitempty"`
		Kind struct {
			Group   string `json:"group,omitempty"`
			Version string `json:"version,omitempty"`
			Kind    string `json:"kind,omitempty"`
		} `json:"kind,omitempty"`
		Resource struct {
			Group    string `json:"group,omitempty"`
			Version  string `json:"version,omitempty"`
			Resource string `json:"resource,omitempty"`
		} `json:"resource,omitempty"`
		RequestKind struct {
			Group   string `json:"group,omitempty"`
			Version string `json:"version,omitempty"`
			Kind    string `json:"kind,omitempty"`
		} `json:"requestKind,omitempty"`
		RequestResource struct {
			Group    string `json:"group,omitempty"`
			Version  string `json:"version,omitempty"`
			Resource string `json:"resource,omitempty"`
		} `json:"requestResource,omitempty"`
		Namespace string `json:"namespace,omitempty"`
		Operation string `json:"operation,omitempty"`
		UserInfo  struct {
			Username string   `json:"username,omitempty"`
			UID      string   `json:"uid,omitempty"`
			Groups   []string `json:"groups,omitempty"`
		} `json:"userInfo,omitempty"`
		Object struct {
			Kind       string `json:"kind,omitempty"`
			APIVersion string `json:"apiVersion,omitempty"`
			Metadata   struct {
				GenerateName      string `json:"generateName,omitempty"`
				CreationTimestamp any    `json:"creationTimestamp,omitempty"`
				Labels            struct {
					App             string `json:"app,omitempty"`
					Capper          string `json:"capper,omitempty"`
					PodTemplateHash string `json:"pod-template-hash,omitempty"`
				} `json:"labels,omitempty"`
				Annotations struct {
					Capper                         string `json:"capper,omitempty"`
					KubectlKubernetesIoRestartedAt string `json:"kubectl.kubernetes.io/restartedAt,omitempty"`
				} `json:"annotations,omitempty"`
				OwnerReferences []struct {
					APIVersion         string `json:"apiVersion,omitempty"`
					Kind               string `json:"kind,omitempty"`
					Name               string `json:"name,omitempty"`
					UID                string `json:"uid,omitempty"`
					Controller         bool   `json:"controller,omitempty"`
					BlockOwnerDeletion bool   `json:"blockOwnerDeletion,omitempty"`
				} `json:"ownerReferences,omitempty"`
				ManagedFields []struct {
					Manager    string    `json:"manager,omitempty"`
					Operation  string    `json:"operation,omitempty"`
					APIVersion string    `json:"apiVersion,omitempty"`
					Time       time.Time `json:"time,omitempty"`
					FieldsType string    `json:"fieldsType,omitempty"`
					FieldsV1   struct {
						FMetadata struct {
							FAnnotations struct {
								NAMING_FAILED struct {
								} `json:".,omitempty"`
								FCapper struct {
								} `json:"f:capper,omitempty"`
								FKubectlKubernetesIoRestartedAt struct {
								} `json:"f:kubectl.kubernetes.io/restartedAt,omitempty"`
							} `json:"f:annotations,omitempty"`
							FGenerateName struct {
							} `json:"f:generateName,omitempty"`
							FLabels struct {
								NAMING_FAILED struct {
								} `json:".,omitempty"`
								FApp struct {
								} `json:"f:app,omitempty"`
								FCapper struct {
								} `json:"f:capper,omitempty"`
								FPodTemplateHash struct {
								} `json:"f:pod-template-hash,omitempty"`
							} `json:"f:labels,omitempty"`
							FOwnerReferences struct {
								NAMING_FAILED struct {
								} `json:".,omitempty"`
								KUIDCc59Bc1D929342EeB20E454067Ab6C0F struct {
								} `json:"k:{"uid":"cc59bc1d-9293-42ee-b20e-454067ab6c0f"},omitempty"`
							} `json:"f:ownerReferences,omitempty"`
						} `json:"f:metadata,omitempty"`
						FSpec struct {
							FContainers struct {
								KNameBelowtestm struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"belowtestm"},omitempty"`
								KNameCentos struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"centos"},omitempty"`
								KNameTestabove struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"testabove"},omitempty"`
								KNameTestaboveM struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"testabove-m"},omitempty"`
								KNameTestmatching struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"testmatching"},omitempty"`
								KNameTestmatchingM struct {
									NAMING_FAILED struct {
									} `json:".,omitempty"`
									FImage struct {
									} `json:"f:image,omitempty"`
									FImagePullPolicy struct {
									} `json:"f:imagePullPolicy,omitempty"`
									FName struct {
									} `json:"f:name,omitempty"`
									FResources struct {
										NAMING_FAILED struct {
										} `json:".,omitempty"`
										FLimits struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:limits,omitempty"`
										FRequests struct {
											NAMING_FAILED struct {
											} `json:".,omitempty"`
											FCPU struct {
											} `json:"f:cpu,omitempty"`
											FMemory struct {
											} `json:"f:memory,omitempty"`
										} `json:"f:requests,omitempty"`
									} `json:"f:resources,omitempty"`
									FStdin struct {
									} `json:"f:stdin,omitempty"`
									FTerminationMessagePath struct {
									} `json:"f:terminationMessagePath,omitempty"`
									FTerminationMessagePolicy struct {
									} `json:"f:terminationMessagePolicy,omitempty"`
									FTty struct {
									} `json:"f:tty,omitempty"`
								} `json:"k:{"name":"testmatching-m"},omitempty"`
							} `json:"f:containers,omitempty"`
							FDNSPolicy struct {
							} `json:"f:dnsPolicy,omitempty"`
							FEnableServiceLinks struct {
							} `json:"f:enableServiceLinks,omitempty"`
							FRestartPolicy struct {
							} `json:"f:restartPolicy,omitempty"`
							FSchedulerName struct {
							} `json:"f:schedulerName,omitempty"`
							FSecurityContext struct {
							} `json:"f:securityContext,omitempty"`
							FTerminationGracePeriodSeconds struct {
							} `json:"f:terminationGracePeriodSeconds,omitempty"`
						} `json:"f:spec,omitempty"`
					} `json:"fieldsV1,omitempty"`
				} `json:"managedFields,omitempty"`
			} `json:"metadata,omitempty"`
			Spec struct {
				Volumes []struct {
					Name      string `json:"name,omitempty"`
					Projected struct {
						Sources []struct {
							ServiceAccountToken struct {
								ExpirationSeconds int    `json:"expirationSeconds,omitempty"`
								Path              string `json:"path,omitempty"`
							} `json:"serviceAccountToken,omitempty"`
							ConfigMap struct {
								Name  string `json:"name,omitempty"`
								Items []struct {
									Key  string `json:"key,omitempty"`
									Path string `json:"path,omitempty"`
								} `json:"items,omitempty"`
							} `json:"configMap,omitempty"`
							DownwardAPI struct {
								Items []struct {
									Path     string `json:"path,omitempty"`
									FieldRef struct {
										APIVersion string `json:"apiVersion,omitempty"`
										FieldPath  string `json:"fieldPath,omitempty"`
									} `json:"fieldRef,omitempty"`
								} `json:"items,omitempty"`
							} `json:"downwardAPI,omitempty"`
						} `json:"sources,omitempty"`
						DefaultMode int `json:"defaultMode,omitempty"`
					} `json:"projected,omitempty"`
				} `json:"volumes,omitempty"`
				Containers []struct {
					Name      string `json:"name,omitempty"`
					Image     string `json:"image,omitempty"`
					Resources struct {
						Limits struct {
							CPU    string `json:"cpu,omitempty"`
							Memory string `json:"memory,omitempty"`
						} `json:"limits,omitempty"`
						Requests struct {
							CPU    string `json:"cpu,omitempty"`
							Memory string `json:"memory,omitempty"`
						} `json:"requests,omitempty"`
					} `json:"resources,omitempty"`
					VolumeMounts []struct {
						Name      string `json:"name,omitempty"`
						ReadOnly  bool   `json:"readOnly,omitempty"`
						MountPath string `json:"mountPath,omitempty"`
					} `json:"volumeMounts,omitempty"`
					TerminationMessagePath   string `json:"terminationMessagePath,omitempty"`
					TerminationMessagePolicy string `json:"terminationMessagePolicy,omitempty"`
					ImagePullPolicy          string `json:"imagePullPolicy,omitempty"`
					Stdin                    bool   `json:"stdin,omitempty"`
					Tty                      bool   `json:"tty,omitempty"`
				} `json:"containers,omitempty"`
				RestartPolicy                 string `json:"restartPolicy,omitempty"`
				TerminationGracePeriodSeconds int    `json:"terminationGracePeriodSeconds,omitempty"`
				DNSPolicy                     string `json:"dnsPolicy,omitempty"`
				ServiceAccountName            string `json:"serviceAccountName,omitempty"`
				ServiceAccount                string `json:"serviceAccount,omitempty"`
				SecurityContext               struct {
				} `json:"securityContext,omitempty"`
				SchedulerName string `json:"schedulerName,omitempty"`
				Tolerations   []struct {
					Key               string `json:"key,omitempty"`
					Operator          string `json:"operator,omitempty"`
					Effect            string `json:"effect,omitempty"`
					TolerationSeconds int    `json:"tolerationSeconds,omitempty"`
				} `json:"tolerations,omitempty"`
				Priority           int    `json:"priority,omitempty"`
				EnableServiceLinks bool   `json:"enableServiceLinks,omitempty"`
				PreemptionPolicy   string `json:"preemptionPolicy,omitempty"`
			} `json:"spec,omitempty"`
			Status struct {
			} `json:"status,omitempty"`
		} `json:"object,omitempty"`
		OldObject any  `json:"oldObject,omitempty"`
		DryRun    bool `json:"dryRun,omitempty"`
		Options   struct {
			Kind       string `json:"kind,omitempty"`
			APIVersion string `json:"apiVersion,omitempty"`
		} `json:"options,omitempty"`
	} `json:"request,omitempty"`
}
