---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-webhook
  namespace: test-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-webhook
  namespace: test-webhook
subjects:
  - kind: ServiceAccount
    name: test-webhook
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin # FOR LOCAL TESTING
  apiGroup: rbac.authorization.k8s.io
