---
apiVersion: v1
kind: Service
metadata:
  name: test-webhook
  namespace: test-webhook
spec:
  # type: ExternalName
  externalName: test-webhook.test-webhook.svc
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: test-webhook
