---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
 name: "test-webhook"
 annotations:
    certmanager.k8s.io/inject-ca-from: "test-webhook/test-webhook-root-cert"
    cert-manager.io/inject-ca-from: "test-webhook/test-webhook-root-cert"
webhooks:
- name: "test-webhook.test-webhook.svc"
  namespaceSelector:
    matchLabels:
      test-webhook-admission-webhook: enabled
  failurePolicy: Ignore
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "*"
  clientConfig:
    service:
      namespace: test-webhook
      name: test-webhook
      path: /post
      port: 443
    # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRREdWQWNCVHdDTUNEQU5CZ2txaGtpRzl3MEJBUXNGQURBdk1TMHdLd1lEVlFRRERDUkIKWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlySUVSbGJXOGdRMEV3SGhjTk1qSXdOVEF5TVRVeQpORFEwV2hjTk1qSXdOakF4TVRVeU5EUTBXakF2TVMwd0t3WURWUVFERENSQlpHMXBjM05wYjI0Z1EyOXVkSEp2CmJHeGxjaUJYWldKb2IyOXJJRVJsYlc4Z1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ3l3M3c4bXdkZkhibGJRb0pOU1JxTG1qUHQ0QkpkNXlaTlFzbkZIa25Rc2FWYnNreDFKbGRQbVk3bAo0ejhuSXpXQWhJc2pjUU55R2lXT3NvNENBa0UwbjNoYUx2ZlhYSW9VYWFZa1FITHh6RXZtcHE2OGs4UDBaRERGCm84akk4ZG40T2I2ZGF1cXFJWnRxV21aelJNQWIzTHZ0Rkk1b3dLSElCeTd3emtuZGJINTVIVlk1OEZpNm9xM3AKZVlPZWdvRDdybWZUdEluU1lzdGswUXFjbUZVblVQV0R1MjJ4RVprT1lVVDNHcUpEdjlML2RVT0VudzF5WE5nYQpGWnk4VWNyNkE5c0M0T0tMYkFmYU92eUVnRDRKazJiNnpCWDh1YnUxaXcrU2JLamlOcDg3ZkNaQU9RL1N2NUlCClorbzBGUzlycWl1Z1F1RW00ZkdWUmdCSGxuazVBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHSUIKOXA3SnRCR1AzQmVkRExMVnl5bjVqWkxnV1RBSGQweGhTdkZ3UG9UN2VVNDQzWitVU1FiTFdUeGRQWmdBRjMycgo0VldwUFpCZGFaRU5Kcnh3UjB5bzlJVkFQOG40WGo3RW5aYmZFRi9VR3Zld3pKTFVCSGtLVFhvQmI2dk9lMVdxClNDM3FlWlBVT2MrZW9BemVsZS9laFVwSlNmQkw2cnVWNHkwMFNUNVVzM0txNlB6RnExSVVGcFo2T3phQks5bmEKZDVlY0NCSmx3N3M0T0hrZmhtbU9KUVpZdWFDYk9YQkVnd3VvV3puRDhWVGFpV1Y0TVFlb2RzNHFIZ2dUd09vTQpDRE5uYk9MdzJzM3pxa281ZkhMZlRGZ0hKU2dxYjYxaldvRGRLSXRmWGlVRFhodnljUStIZ1FRL2kyTWpiMkM1CmpOZTNpL1BoQ2c1NHh1T29wTVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  admissionReviewVersions: ["v1"]
  sideEffects: None
# ---
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#  name: "test-webhook"
#  annotations:
#     certmanager.k8s.io/inject-ca-from: "test-webhook/test-webhook-root-cert"
#     cert-manager.io/inject-ca-from: "test-webhook/test-webhook-root-cert"
# webhooks:
# - name: "test-webhook.test-webhook.svc"
#   namespaceSelector:
#     matchLabels:
#       test-webhook-admission-webhook: enabled
#   failurePolicy: Ignore
#   rules:
#   - apiGroups: [""]
#     apiVersions: ["v1"]
#     operations: ["CREATE"]
#     resources: ["pods"]
#     scope: "*"
#   clientConfig:
#     service:
#       namespace: test-webhook
#       name: test-webhook
#       path: /post
#       port: 443
#     # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRREdWQWNCVHdDTUNEQU5CZ2txaGtpRzl3MEJBUXNGQURBdk1TMHdLd1lEVlFRRERDUkIKWkcxcGMzTnBiMjRnUTI5dWRISnZiR3hsY2lCWFpXSm9iMjlySUVSbGJXOGdRMEV3SGhjTk1qSXdOVEF5TVRVeQpORFEwV2hjTk1qSXdOakF4TVRVeU5EUTBXakF2TVMwd0t3WURWUVFERENSQlpHMXBjM05wYjI0Z1EyOXVkSEp2CmJHeGxjaUJYWldKb2IyOXJJRVJsYlc4Z1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ3l3M3c4bXdkZkhibGJRb0pOU1JxTG1qUHQ0QkpkNXlaTlFzbkZIa25Rc2FWYnNreDFKbGRQbVk3bAo0ejhuSXpXQWhJc2pjUU55R2lXT3NvNENBa0UwbjNoYUx2ZlhYSW9VYWFZa1FITHh6RXZtcHE2OGs4UDBaRERGCm84akk4ZG40T2I2ZGF1cXFJWnRxV21aelJNQWIzTHZ0Rkk1b3dLSElCeTd3emtuZGJINTVIVlk1OEZpNm9xM3AKZVlPZWdvRDdybWZUdEluU1lzdGswUXFjbUZVblVQV0R1MjJ4RVprT1lVVDNHcUpEdjlML2RVT0VudzF5WE5nYQpGWnk4VWNyNkE5c0M0T0tMYkFmYU92eUVnRDRKazJiNnpCWDh1YnUxaXcrU2JLamlOcDg3ZkNaQU9RL1N2NUlCClorbzBGUzlycWl1Z1F1RW00ZkdWUmdCSGxuazVBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHSUIKOXA3SnRCR1AzQmVkRExMVnl5bjVqWkxnV1RBSGQweGhTdkZ3UG9UN2VVNDQzWitVU1FiTFdUeGRQWmdBRjMycgo0VldwUFpCZGFaRU5Kcnh3UjB5bzlJVkFQOG40WGo3RW5aYmZFRi9VR3Zld3pKTFVCSGtLVFhvQmI2dk9lMVdxClNDM3FlWlBVT2MrZW9BemVsZS9laFVwSlNmQkw2cnVWNHkwMFNUNVVzM0txNlB6RnExSVVGcFo2T3phQks5bmEKZDVlY0NCSmx3N3M0T0hrZmhtbU9KUVpZdWFDYk9YQkVnd3VvV3puRDhWVGFpV1Y0TVFlb2RzNHFIZ2dUd09vTQpDRE5uYk9MdzJzM3pxa281ZkhMZlRGZ0hKU2dxYjYxaldvRGRLSXRmWGlVRFhodnljUStIZ1FRL2kyTWpiMkM1CmpOZTNpL1BoQ2c1NHh1T29wTVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#   admissionReviewVersions: ["v1"]
#   sideEffects: None
